### ISSUE TITLE
Inconsistent magnitudes ?

### ISSUE THREAD

**Issue by fhenryco** [dscolnic/Pantheon#5]
![magP-magJ_2](https://user-images.githubusercontent.com/20909200/67019276-b32ce700-f0fc-11e9-9c29-9a939a736268.png)

![magP-magJ](https://user-images.githubusercontent.com/20909200/67019685-5c73dd00-f0fd-11e9-86e6-1ce0ae37854b.png)

For SNs that are in common in JLA and Pantheon , the difference of mb magnitudes as a function of redshift is plotted (after "normalisation" to zero).
I m trying to understand the origin of such huge differences in particular for SDSS, since this does not look like the effect of the new  supercal calibration as documented in figure 7 of https://iopscience.iop.org/article/10.1088/0004-637X/815/2/117/pdf 

This difference is responsible for a dramatic shift in the fitted theoretical parameters for the theory i'm testing (much bigger shift than for the fit of LCDM parameters ).

So if its is not calibration what is it ?  if it's the new analysis (light curve fitting) why does it affect the SDSS supernovae much more than the SNLS ones ?

thanks in advance for any helpfull suggestion
best regards

**Comment by dscolnic** [comment]
Hi - just seeing this and thanks for this post.  I have changed a number of things from JLA, so I don't know exactly what I would have expected here - but the biggest change is due to using: the method in this paper - https://arxiv.org/abs/1610.04677.

This changes individual SN distances depending on their observe properties, effectively using a prior for their properties.    The other really big thing I changed was that affects low-redshift more than SNLS is that I added a different model for the intrinsic scatter (what's called C11) in my paper because we just don't know the true underlying scatter model, and that affects the distance recovery.  To chase this down, you may want to check:
 https://github.com/dscolnic/Pantheon/blob/master/data_fitres/Ancillary_G10.FITRES  -- I would check two things, one - the mu values as given, and two, the distance modulus if you use Tripp estimator yourself (and apply no bias corrections), and use the same alpha and beta as with JLA.  Hope this helps!

**Comment by fhenryco** [comment]
Hi and thank you for your answer,
I also could not find the reason why the HST magnitudes are now all lying ~50mmag below the JLA ones, something i also noticed on other recent samples (such as Yonsei). This looks more like a calibration correction but i did not find where it comes from. A word on that ?
regards,
Fred

**Comment by dscolnic** [comment]
Sorry, this I'm not sure of...

**Comment by fhenryco** [comment]
I just want to specify that i'm actually comparing the mb from your Ancillary_C11.FITRES file to the JLA mb. I also checked other variables but then the discrepency and dispersion are much larger as expected because the Tripp estimator formula is not applied exactly in the same way as in JLA, so i was not surprised. I'm only surprised by the different mb magnitudes : this could not be  due to contamination corrections for those common SN which are spectroscopically identified, while i was expecting bias corrections (not affecting the mb given in JLA) to increase the corrected mb in Pantheon relative to JLA if correction only applied in Pantheon : does not seem to be the case for SNLS neither for HST SNs. So the only explanation i could find was that the great differences in mb are produced by the fact that you recalibrated the SNs without accordingly recalibrating SALT2 as you mention :"This work does not achieve the maximum possible reduction
of systematic biases from the Supercal approach,
because the SALT2 model was trained and calibrated using
a SN sample that was not recalibrated using the Supercal
method."

**Comment by dscolnic** [comment]
Ah- that makes more sense that this is an mb to mb comparison.  I did not understand.  JLA's mb I thought wasn't measured mb but corrected mb.  I'm going to email and take this offline.
